import pickle
import tensorflow as tf

def load(sess,_weights,_bias, model_path):
    f = open(model_path,'rb')
    model = pickle.load(f
            ,encoding='iso-8859-1')
            #)
    # (newChannel,oldChannel,Time,Height,Width)
    # transpose to
    # (Time,Height,Width,oldChannel,newChannel)
    # so
    # (0,1,2,3,4) - > (2,3,4,1,0)
    update = tf.assign(_weights['wc1'], model['conv1a_0'].transpose([2,3,4,1,0]))
    sess.run(update)
    update = tf.assign(_weights['wc2'], model['conv2a_0'].transpose([2,3,4,1,0]))
    sess.run(update)
    update = tf.assign(_weights['wc3a'] , model['conv3a_0'].transpose([2,3,4,1,0]))
    sess.run(update)
    update = tf.assign(_weights['wc4a'] , model['conv4a_0'].transpose([2,3,4,1,0]))
    sess.run(update)
    update = tf.assign(_weights['wc5a'] , model['conv5a_0'].transpose([2,3,4,1,0]))
    sess.run(update)
    update = tf.assign(_weights['wd1'] ,model['fc6_0'].transpose([1,0]))
    sess.run(update)
    update = tf.assign(_weights['wd2'] , model['fc7_0'].transpose([1,0]))
    sess.run(update)
    update = tf.assign(_bias['bc1'] , model['conv1a_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bc2'] , model['conv2a_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bc3a'] , model['conv3a_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bc4a'] , model['conv4a_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bc5a'] , model['conv5a_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bd1'] , model['fc6_1'].ravel())
    sess.run(update)
    update = tf.assign(_bias['bd2'] , model['fc7_1'].ravel())
    sess.run(update)
    print('Load %s Done.' % model_path)
